version: '3'

services:
  reverse-proxy:
    image: traefik # The official Traefik docker image
    container_name: tripbff-traefik
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    ports:
      - "80:80"     # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to 

  whoami:
    image: containous/whoami # A container that exposes an API to show its IP address
    # container_name: tripbff-whoami
    labels:
      - "traefik.frontend.rule=Host:whoami.docker.localhost"
      - "traefik.backend.rule=Host:whoami.docker.localhost"

  # whoami2:
  #   image: containous/whoami # A container that exposes an API to show its IP address
  #   # container_name: tripbff-whoami
  #   labels:
  #     - "traefik.backend.rule=Host:whoami-api.localhost"